CREATE TABLE [dbo].[GeocodingResults](
	[Location] [nvarchar](100) NOT NULL,
	[Latitude] [money] NULL,
	[Longitude] [money] NULL,
	[DateCreated] [datetime] NOT NULL DEFAULT(GetUtcDate())
 CONSTRAINT [PK_GeocodingResults] PRIMARY KEY CLUSTERED 
(
	[Location] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('HERTFORD, UNITED KINGDOM',-0.08,51.80)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NORTHERN IRELAND',-6.49,54.79)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('PHILADELPHIA',-75.16,39.95)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('LONDON, UNITED KINGDOM',-0.13,51.51)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SARASOTA, FL',-82.53,27.34)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ONTARIO, CANADA',-85.32,51.25)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('JOHANNESBURG, SOUTH AFRICA',28.05,-26.20)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SWITZERLAND',8.23,46.82)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('POLAND',19.15,51.92)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BROOKLYN, NY',-73.95,40.65)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('TEHRAN, IRAN',51.42,35.70)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MONTREAL, CANADA',-73.55,45.51)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('EVERYWHERE',-91.85,37.67)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SURABAYA, INDONESIA',112.73,-7.29)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('GREECE',21.82,39.07)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NORTH POLE, AK',-147.35,64.75)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SAN ANTONIO, TX',-98.49,29.42)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('INDIA',78.96,20.59)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('HOLLYWOOD, UNITED KINGDOM',-1.88,52.40)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BRIGHTON, UNITED KINGDOM',-0.13,50.84)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BELGIUM',4.47,50.50)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('COVENTRY, UNITED KINGDOM',-1.52,52.41)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('WESTERN EUROPE',1.26,46.20)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('DEXTER, MI',-83.89,42.34)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MUMBAI, INDIA',72.88,19.08)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('QUEBEC',-73.55,52.94)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('UNITED STATES',-95.71,37.09)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MALAYSIA',101.98,4.21)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('YORK, UNITED KINGDOM',-1.08,53.96)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('COIMBATORE, INDIA',76.96,11.02)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('OSLO, NORWAY',10.75,59.91)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('EARTH',-102.41,34.23)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('RUSSIA',105.32,61.52)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('FINLAND',25.75,61.92)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('LONDON',-0.13,51.51)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MADISON, WI',-89.40,43.07)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('TORONTO, CANADA',-79.38,43.65)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ENGLAND, UNITED KINGDOM',-1.17,52.36)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ALEXANDRIA, VA',-77.05,38.80)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('PHILADELPHIA, PA',-75.16,39.95)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SPLIT, CROATIA',16.44,43.51)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('LANSING, MI',-84.56,42.73)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NEBRASKA',-99.90,41.49)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MINNESOTA',-94.69,46.73)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ISRAEL',34.85,31.05)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BANGALORE, INDIA',77.59,12.97)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('HANOVER',-77.37,37.77)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CZECH REPUBLIC',15.47,49.82)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('VIRGINIA',-78.66,37.43)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ARKANSAS',-91.83,35.20)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('STAMFORD, CT',-73.54,41.05)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CELJE, SLOVENIA',15.26,46.23)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ATLANTA GA',-84.39,33.75)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('AMSTERDAM, THE NETHERLANDS',4.90,52.37)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CHILE',-71.54,-35.68)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('HELLO WORLD',100.53,13.73)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('HUDDERSFIELD, UNITED KINGDOM',-1.79,53.65)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SPAIN',-3.75,40.46)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('VALENCIENNES, FRANCE',3.52,50.36)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NEW JERSEY',-74.41,40.06)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BANGKOK, THAILAND',100.66,13.82)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BRAZIL',-51.93,-14.24)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('COLUMBUS, OH',-83.00,39.96)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('PITTSBURGH, PA',-80.00,40.44)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('EARTH, TX',-102.41,34.23)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NEW YORK, NY',-74.01,40.71)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('DUBLIN, IRELAND',-6.27,53.34)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('UNITED KINGDOM',-3.44,55.38)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('COLOMBO, SRI LANKA',79.86,6.93)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('AUSTIN, TX',-97.74,30.27)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('RALEIGH, NC',-78.64,35.77)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('LIMA, PERU',-77.06,-12.05)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BAKU, AZERBAIJAN',49.87,40.44)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('JAIPUR, INDIA',75.79,26.91)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('TAMPA, FL',-82.46,27.95)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('TEXAS',-99.90,31.97)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('GERMANY',10.45,51.17)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NEW YORK, UNITED STATES',-74.01,40.71)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CALIFORNIA',-119.42,36.78)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('HOUSTON, TX',-95.37,29.76)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('JERUSALEM, ISRAEL',35.21,31.77)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('FRANCE',2.21,46.23)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ANYWHERE, USA',-82.40,28.01)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SOUTH KOREA',127.77,35.91)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('DHAKA, BANGLADESH',90.41,23.71)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MANCHESTER, UNITED KINGDOM',-2.25,53.48)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CALGARY, CANADA',-114.06,51.05)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BERLIN, GERMANY',13.41,52.52)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BOULDER, CO',-105.27,40.02)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MINNEAPOLIS',-93.26,44.98)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('VANCOUVER, WA',-122.66,45.64)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MARYLAND',-76.64,39.05)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ROCHESTER, MN',-92.47,44.02)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NETHERLANDS',5.29,52.13)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('TURKEY',35.24,38.96)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ITALY',12.57,41.87)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('KOLKATA, INDIA',88.36,22.57)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SCHIEDAM, NETHERLANDS',4.40,51.92)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SUFFOLK, VA',-76.58,36.73)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('AUBURN, WA',-122.23,47.31)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NASHVILLE, TN',-86.78,36.17)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('HAWAII',-155.58,19.90)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('JULIAN, CA',-116.60,33.08)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('LAS VEGAS, NV',-115.17,36.11)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('KENTUCKY',-84.27,37.84)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('COCHRANE, CANADA',-114.47,51.19)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NORTH DAKOTA',-101.00,47.55)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('WASHINGTON, DC',-77.04,38.90)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('PASADENA, CA',-118.14,34.15)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SURREY, CANADA',-122.83,49.11)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SEATTLE, WA',-122.33,47.61)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SOUTH PLAINFIELD, NJ',-74.41,40.58)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CORVALLIS, OR',-123.26,44.56)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('REDONDO BEACH, CA',-118.39,33.85)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CONNECTICUT',-73.09,41.60)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('TARRYTOWN, NY',-73.86,41.08)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SYDNEY',151.21,-33.87)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('PUNE, INDIA',73.86,18.52)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BUENOS AIRES, ARGENTINA',-58.37,-34.61)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ROCHESTER, NY',-77.61,43.16)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ISTANBUL, TURKEY',28.98,41.01)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CORONA, CA',-117.57,33.88)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CHICAGO, IL',-87.63,41.88)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('FARMVILLE, VA',-78.39,37.30)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MIDLAND, TX',-102.08,32.00)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NORTHWEST, NC',-78.16,34.31)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CUPERTINO, CA',-122.03,37.32)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('PERTH, AUSTRALIA',115.86,-31.95)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NEW YORK, NEW YORK',-74.01,40.71)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ISTANBUL, TURKIYE',28.98,41.01)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SOUTH CAROLINA',-81.16,33.84)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('IRAN',53.69,32.43)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('DARLINGTON, UNITED KINGDOM',-1.56,54.52)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CHESTER, UNITED KINGDOM',-2.89,53.19)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('SAN FRANCISCO, CA',-122.42,37.77)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('LOS ANGELES, CA',-118.24,34.05)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BATH, UNITED KINGDOM',-2.36,51.38)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MANGALORE, INDIA',74.86,12.91)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NOIDA, INDIA',77.39,28.54)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NORTH CAROLINA',-79.02,35.76)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MY COMPUTER',-76.93,40.30)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CHEYENNE, WY',-104.82,41.14)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('DAVENPORT, IA',-90.58,41.52)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MATALE, SRI LANKA',80.62,7.47)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('UNIVERSE',120.99,14.42)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NORTHEAST PA',-77.19,41.20)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CINCINNATI, OH',-84.51,39.10)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('HIGHLAND LAKES, NJ',-74.46,41.18)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('YEKATERINBURG, RUSSIA',60.60,56.85)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CARMEL, IN',-86.12,39.98)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('EDMONTON, CANADA',-113.49,53.54)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('DALLAS, TX',-96.77,32.80)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MADURAI, INDIA',78.12,9.93)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('CALIFORNIA, US',-119.42,36.78)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('FRIBOURG, SWITZERLAND',7.15,46.80)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('WINSTON-SALEM, NC',-80.24,36.10)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ONTARIO',-85.32,51.25)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NEW YORK',-74.01,40.71)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ROMANIA',24.97,45.94)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('LEBANON',35.86,33.85)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MISSOULA, MT',-113.99,46.87)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('BAKERSFIELD, CA',-119.02,35.37)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('JERSEY CITY, NJ',-74.08,40.73)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ASHEVILLE, NC',-82.55,35.60)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('P&#233;CS, HUNGARY',18.23,46.07)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('NORWAY',8.47,60.47)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('HYDERABAD',78.49,17.39)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('MASSACHUSETTS',-71.38,42.41)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('INDONESIA',113.92,-0.79)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('TENNESSEE',-86.58,35.52)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('HONG KONG',114.11,22.40)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ARGENTINA',-63.62,-38.42)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('THE NETHERLANDS',5.29,52.13)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('ANN ARBOR, MI',-83.74,42.28)
INSERT INTO GeocodingResults (Location, Latitude, Longitude) VALUES ('HYDERABAD, INDIA',78.49,17.39)